/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_nekocloud_core_io_compress_zlib_NativeCompressImpl */

#ifndef _Included_me_nekocloud_core_io_compress_zlib_NativeCompressImpl
#define _Included_me_nekocloud_core_io_compress_zlib_NativeCompressImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_nekocloud_core_io_compress_zlib_NativeCompressImpl
 * Method:    initFields
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_nekocloud_core_io_compress_zlib_NativeCompressImpl_initFields
  (JNIEnv *, jclass);

/*
 * Class:     me_nekocloud_core_io_compress_zlib_NativeCompressImpl
 * Method:    end
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_me_nekocloud_core_io_compress_zlib_NativeCompressImpl_end
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     me_nekocloud_core_io_compress_zlib_NativeCompressImpl
 * Method:    reset
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_me_nekocloud_core_io_compress_zlib_NativeCompressImpl_reset
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     me_nekocloud_core_io_compress_zlib_NativeCompressImpl
 * Method:    init
 * Signature: (ZI)J
 */
JNIEXPORT jlong JNICALL Java_me_nekocloud_core_io_compress_zlib_NativeCompressImpl_init
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     me_nekocloud_core_protocol_compress_zlib_NativeCompressImpl
 * Method:    process
 * Signature: (JJIJIZ)I
 */
JNIEXPORT jint JNICALL Java_me_nekocloud_core_io_compress_zlib_NativeCompressImpl_process
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
